version: 2
updates:
  - package-ecosystem: "pip"
    directory: "DevUtils/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "UDKTests/"
    schedule:
      interval: "weekly"
