#!/usr/bin/env python

# MIT License
#
# Copyright (c) 2023 Tuomo Kriikkula
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Processes primes generated by GMP mpz export into UnrealScript
syntax for use in DefaultProperties blocks.
"""

import itertools
from pathlib import Path
from typing import List


def strip_leading_zeros(word: str) -> str:
    """Strip leading 'zero words'.
    00 03 -> 03
    00 45 -> 45
    11 A5 -> 11 A5
    """
    w_split = [w for w in word.split(" ")]
    if len(w_split) == 1:
        return word
    words = []
    leading_zeros = (w_split[0] == "00")
    for ws in w_split:
        leading_zeros = leading_zeros and (ws == "00")
        if not leading_zeros:
            words.append(ws)
    words = [w for w in words if w]
    return " ".join(words)


def split_words(words: List[str]) -> str:
    """Split 2-byte words into 1-byte words.
    'FFFF AAAA' -> 'FF FF AA AA'
    """
    x = [[w[:2], w[2:]] for w in words]
    x_flat = itertools.chain.from_iterable(x)
    xx = " ".join(x_flat)
    return strip_leading_zeros(xx)


def bytes_to_uscript_array(words: str) -> str:
    x = [str(int(w, 16)) for w in words.split(" ")]
    return ",".join(x)


def main():
    primes_in = Path("primes.txt").read_text()
    p_lines = [p for p in primes_in.split("\n") if p]
    p_lines = [p.split(" ") for p in p_lines]
    p_lines = [split_words(p) for p in p_lines]
    p_lines = [
        f"    Primes({i})=(P=({bytes_to_uscript_array(p)}))"
        for i, p in enumerate(p_lines)
    ]
    Path("primes_out.txt").write_text("\n".join(p_lines))
    for pl in p_lines:
        print(pl)


if __name__ == "__main__":
    main()
